### ISSUE TITLE
ID 1.1 Upload a PDF document

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-pdf-consultations#1]
**Is your feature request related to a problem? Please describe.**
Currently, there is no specific component that allows me to upload a PDF. In this PDF, I want participants to be able to make suggestions to improve the text. The primary functionality of this component is to enable PDF uploads.

**Describe the solution you'd like**
A process-admin can upload a PDF document as basis for the participatory interaction.

**Mock up**
Design chose: Option 1: http://projects.pokecode.net/pdf_op1/

**Does this issue could impact on users private data?**
No

**Acceptance criteria**
- [x] As a participatory-admin, I can add a new component called "Participatory PDF"
- [x] As a participatory-admin, I can upload a new PDF from my computer. 

**Technical specifications**
- https://github.com/openpoke/decidim-module-participatory-documents/issues/3
- https://github.com/openpoke/decidim-module-participatory-documents/issues/4
- https://github.com/openpoke/decidim-module-participatory-documents/issues/36

**Implementation**
- [x] https://github.com/openpoke/decidim-module-participatory-documents/pull/2
- [x] https://github.com/openpoke/decidim-module-participatory-documents/pull/5 (fail)
- [x] https://github.com/openpoke/decidim-module-participatory-documents/pull/16
- [x] https://github.com/openpoke/decidim-module-participatory-documents/pull/46

**Testing**
1. Install https://github.com/openpoke/decidim-module-participatory-documents in your app

2. Go to a participatory space and add a new component "Participatory PDF"
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/4824826c-79c5-4175-828d-f664817b3eb3)

3. Configure the settings for the component
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/0dd2033c-fc46-469d-97bc-6db0f4fc07a5)

4. Go to upload the document as a PDF
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/d8caa2bf-f7d6-46c5-8941-371bfe7af2ed)

5. Upload your PDF and create the Participatory document
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/81689ff0-2893-40ac-89b9-9dc4b9a70095)

**Additional context**
If you want to follow the flow-test, see

**Comment by paarals** [comment]
hi @Naadjjaa, you have the links on top to decide which option you goes.

**Comment by Naadjjaa** [comment]
Hi @paarals. We would like to go with option 1. The reason is, that with option 2 we see no posibility to filter e.g. by author of the suggestions. If for example a person calls us and we need to see an overview of their suggestions it is not possible in option 2. (By the way, is the filtering for a specific person already an issue?)

**Comment by paarals** [comment]
closed for complete and update info testing
