### ISSUE TITLE
ID2.3 Preview and publish final participatory sections 

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-pdf-consultations#33]
#Open discussion, feel free to collaborate

Situation 1: Close the edition before participation
-The sections are well ordered.
-We block potential inconsistencies and incidents if sections with suggestions are edited
-We win security

How do we do it?
-Add a button that says "Final publication of sections" -> This action means that you will not be able to edit the document or create new sections, are you sure?

**Flow to do**
1. When I finish the participatory areas with sections I see a button which I can preview the PDF in the frontend. 
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/c5ec8593-04d7-4688-89ee-a07d6298b747)

2.1 If I like how it appears, I can publicate sections (Warning message: This action is not reversible. You won't be able to edit anymore areas. Are you sure of this action? 

![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/18454651-af87-4d8c-b460-b417fce7224c)

3.1 I go back to Suggestions dashboard with only one button "See participatory sections" but YOU CAN'T EDIT.  
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/cfd89ae9-036c-48ac-91bf-27020cb1576f)

2.2 If I don't like, I can return to the backend to edit more the areas.

**Comment by Naadjjaa** [comment]
I would choose option 1. That way its consistant with how surverys work. Only thing: Preview needs to be possible before using the button final publication of sections.
