### ISSUE TITLE
ID14.3 As a user, can I find easily my suggestions?

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-pdf-consultations#34]
Let's imagine a situation where we have more than 30 sections. As a user, I made 4 suggestions, but I can't remember which section. I want to review them, where can I see them?

![Image](https://user-images.githubusercontent.com/40388743/226593771-c4b84990-e1a2-4e47-93c3-7fe93a91c5d4.png)

Solution 1:
https://user-images.githubusercontent.com/40388743/228781405-1ed4833f-6424-492b-a925-8bd70eab2a07.mp4

Button to expand the list (we can do a different style to make it intuitive to expand the list. For example, using an icon.

The list is made like hashtags for quick access to the necessary content. When you click, you can open the suggestions for that section.

This approach does not take a lot of space on the page and makes it accessible and understandable to navigate between sections where there is a user's suggestions. If the user wants, the content can be quickly hidden.

![imatge](https://user-images.githubusercontent.com/40388743/228781510-abed21be-2568-42bd-aecc-fef166578919.png)

**Final mockup:**
![image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/1401520/f694da08-4d67-4e28-89a8-a0620bd000b9)

**Comment by Naadjjaa** [comment]
Did you have any new ideas concerning this?
Is it possible to add a button for the user to export his suggestions in pdf format?

**Comment by microstudi** [comment]
I'm leaving here a mockup of how we could add a button that can scale in the future in case there are more options, it should be self-explanatory:

Options button, to be displayed only if the user has made some suggestions:
![Screenshot from 2023-06-19 13-49-45](https://github.com/stadtluzern/decidim-pdf-consultations/assets/1401520/b37f0de1-4123-4a37-9411-3ce37e26ff3d)

Once, "options" is clicked:
![image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/1401520/59fff266-b5bc-4a5c-901c-84d16e213fe2)

**Comment by paarals** [comment]
Perfect Ivan, tell us your inputs @Naadjjaa

**Comment by von** [comment]
> Perfect Ivan, tell us your inputs @von Ballmoos Nadja ***@***.***> and @rast Nicolas ***@***.***> El dl., 19 de juny 2023, 13:52, Ivan Vergés ***@***.***> va escriure:

Wrong '@von' referenced.

**Comment by Naadjjaa** [comment]
@microstudi @paarals Thank you, I understand your thought of making future options possible. Just from a user perspective from my experience I think it is too complicated. I would prefer to have the button to always appear. In case in future we add more functionalities we can still rethink the design. But for now I see no other necessary interaction.

**Comment by microstudi** [comment]
Just a "export my suggestions" next to "global suggestions" then? maybe we can use an icon with a hover title if we want to keep it small

**Comment by Naadjjaa** [comment]
Exactly. I would prefer to have a text button. I agree that it would look better with an icon but the general user of our tool needs so much help if its not self-explanatory. And I know its a function many will use. It gives them an important sense of security.

**Comment by microstudi** [comment]
Ok, so final mockup:
![image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/1401520/2cd6440d-f7da-4ac4-bf93-7e96eb8edd04)

**Comment by Naadjjaa** [comment]
@microstudi Perfect!
